"use strict";

/**
 * Generate a standalone Puppeteer script from a recording. The output is a
 * runnable Node.js file that opens a browser, navigates to the recording's
 * start URL, and replays the captured events with their original inter-event
 * timing.
 */
function generateScript(rec) {
  const BTN = (b) => (b === "right" ? "'right'" : b === "middle" ? "'middle'" : "'left'");
  const lines = [
    `'use strict';`,
    `// Generated by Browser Automation Tool`,
    `// Recording : ${rec.name}  |  URL: ${rec.url}  |  Events: ${rec.events.length}`,
    ``,
    `const puppeteer = require('puppeteer');`,
    `(async () => {`,
    `  const browser = await puppeteer.launch({ headless: false, defaultViewport: null });`,
    `  const [page] = await browser.pages();`,
    `  await page.goto(${JSON.stringify(rec.url)}, { waitUntil: 'domcontentloaded' });`,
    ``,
  ];
  let prevT = 0;
  for (const ev of rec.events) {
    const d = Math.max(0, (ev.t ?? 0) - prevT);
    prevT = ev.t ?? 0;
    if (d > 0) lines.push(`  await new Promise(r => setTimeout(r, ${d}));`);
    switch (ev.type) {
      case "navigate":
        lines.push(`  await page.goto(${JSON.stringify(ev.url)}, { waitUntil: 'domcontentloaded' });`);
        break;
      case "click":
        lines.push(`  await page.mouse.click(${ev.x}, ${ev.y}, { button: ${BTN(ev.button)} });`);
        break;
      case "dblclick":
        lines.push(`  await page.mouse.click(${ev.x}, ${ev.y}, { clickCount: 2 });`);
        break;
      case "wheel":
        lines.push(`  await page.mouse.wheel({ deltaX: ${ev.deltaX}, deltaY: ${ev.deltaY} });`);
        break;
      case "scroll":
        lines.push(`  await page.evaluate(() => window.scrollTo(${ev.scrollX}, ${ev.scrollY}));`);
        break;
      case "keydown":
        lines.push(`  await page.keyboard.down(${JSON.stringify(ev.key)});`);
        break;
      case "keyup":
        lines.push(`  await page.keyboard.up(${JSON.stringify(ev.key)});`);
        break;
      case "input":
        lines.push(`  await page.keyboard.down('Control'); await page.keyboard.press('a'); await page.keyboard.up('Control');`);
        lines.push(`  await page.keyboard.type(${JSON.stringify(ev.value ?? "")});`);
        break;
    }
  }
  lines.push(`  await browser.close();`);
  lines.push(`})().catch(err => { console.error(err); process.exit(1); });`);
  return lines.join("\n");
}

module.exports = { generateScript };
